#ifndef BUTTONSPRITES_H
#define BUTTONSPRITES_H

enum LButtonSprite
{
    BUTTON_SPRITE_MOUSE_OUT,
    BUTTON_SPRITE_MOUSE_OVER_MOTION,
    BUTTON_SPRITE_MOUSE_DOWN,
    BUTTON_SPRITE_MOUSE_UP,
    
    BUTTON_SPRITE_TOTAL,
};

#endif